### ISSUE TITLE
Favicon's Changing

### ISSUE THREAD

**Issue by dotdissent** [BrowserWorks/waterfox#236]
![image](https://user-images.githubusercontent.com/17419460/31261022-d2fcab22-aa1f-11e7-815e-c3676e630bf7.png)

Favicons in my Bookmark Toolbar randomly become Favicons of other sites if I navigate to webpages within the site. In the above case, this is a Reddit bookmark. I clicked a RollingStone.com article within Reddit and the Favicon suddenly changed. I have tried clearing cache and re-adding the bookmark, but the only ways I've found to fix it is to use the "Forget About This Site" All History feature or clear all of my bookmark icons with an add-on like "Delete Bookmark Icons."

This has occurred three times for me now since I switched from Cyberfox to Waterfox a month ago and the last time, Reddit's icon became Youtube's.

**Comment by grahamperrin** [comment]
Is this reproducible with Waterfox 56.0?

**Comment by dotdissent** [comment]
I have been using 56.0 since release and haven't seen this issue
replicated. I believe this can be closed.

On Dec 8, 2017 5:19 PM, "Graham Perrin" <notifications@github.com> wrote:

Is this reproducible with Waterfox 56.0?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/MrAlex94/Waterfox/issues/236#issuecomment-350386389>,
or mute the thread

**Comment by mzso** [comment]
Favicons have been a hot stinking pile of mess since https://bugzilla.mozilla.org/show_bug.cgi?id=977177 landed.

I also get wrong favicons, and not just for bookmarks.  I get an old aliexpress icon when I modify an aliexpress bookmark url.
I got the inoreader icon changed for most history items changed to one of the websites that are added as a feed. And a number of other stuff I didn't make note of.

**Comment by mzso** [comment]
@dotdissent 
Did you happen to test with FF57+ (or follow bugs landed since 56)?
Maybe they fixed some of it that could be uplifted...

**Comment by zalacer** [comment]
I just installed 56.0.4.1 and loaded the profile of the old version of Firefox (45.0.1) I had been using into it including Classic Theme Restorer and other add-ons. This restored my bookmarks toolbar including favicons perfectly except for Google Finance that now shows as a G icon instead of a green square.  Bookmark Favicon Changer won't change this favicon, Favicon Restorer didn't help, and Bookmarks Favicon Images is incompatible. This isn't a big deal, but it would be nice to be able to change favicons, since that's how I recognize websites in the always-visible portion of my bookmarks toolbar that contains 86 bookmarks with distinct favicons excluding 6 Google websites that have the same G favicon. Since IdentFavicon works, this seems to be mostly an issue with Google and I will send them a suggestion about it, however it's sometimes useful to replace an IdentFavicon with something more recognizable like a Q favicon for quantumonline.com.

**Comment by mzso** [comment]
[**@zalacer**](https://github.com/zalacer) commented on [2018. márc. 9. 20:11 CET](https://github.com/MrAlex94/Waterfox/issues/236#issuecomment-371916033 "2018-03-09T19:11:23Z - Replied by Github Reply Comments"):
> I just installed 56.0.4.1 and loaded the profile of the old version of Firefox (45.0.1) I had been using into it including Classic Theme Restorer and other add-ons. This restored my bookmarks toolbar including favicons perfectly except for Google Finance that now shows as a G icon instead of a green square.  Bookmark Favicon Changer won't change this favicon, Favicon Restorer didn't help, and Bookmarks Favicon Images is incompatible. 

Get used to it. Even worse some website favicons will change to a completely different website's favicon and stay that way. 
Just look at what happened to inoreader for me:

![inor-icon](https://user-images.githubusercontent.com/4479090/37226947-e0158f14-23db-11e8-9800-a5b1d263de21.png)

**Comment by zalacer** [comment]
@mzso 

Thanks for the info.  In that case I will go back to the old version of firefox that doesn't have favicon issues.

**Comment by mzso** [comment]
[**@zalacer**](https://github.com/zalacer) commented on [2018. márc. 9. 21:12 CET](https://github.com/MrAlex94/Waterfox/issues/236#issuecomment-371932389 "2018-03-09T20:12:27Z - Replied by Github Reply Comments"):
> [@mzso](https://github.com/mzso)
> 
> Thanks for the info.  In that case I will go back to the old version of firefox that doesn't have favicon issues.

Well, you might want to think twice about that, unless you made a backup. Downgrading can cause pretty nasty issues.
I know for a fact that you will lose all your favicons because in FF55 they were moved from places.sqlite into their own database. (The same time these favicon issues appeared)

**Comment by zalacer** [comment]
@mzso 

I'm already back to firefox 45 and was in fact running it in parallel with waterfox when configuring the latter. The waterfox installation only read the firefox profile. Anyway I backup my firefox profile last thing *every* day.

**Comment by mzso** [comment]
I asked on bugzilla if there were any improvements. These bugs were mentioned: 
Bug 1449523, Bug 1403829, Bug 1422289, Bug 1401777, Bug 1402373, Bug 1401851

There's supposed to be more. Sadly there's no tracking bug...

**Comment by grahamperrin** [comment]
Thanks, 

Mozilla bug [120352 - Site icon (favicon) tracking bug](https://bugzilla.mozilla.org/show_bug.cgi?id=120352) – [dependency tree](https://bugzilla.mozilla.org/showdependencytree.cgi?id=120352&hide_resolved=1)

– and some metadata: 

- [1401777 - Favicons looking bad in Nightly 57](https://bugzilla.mozilla.org/show_bug.cgi?id=1401777&sourceid=Mozilla-search)  RESOLVED FIXED in Firefox 57
- [1401851 - Yahoo favicon / rich-icon is black](https://bugzilla.mozilla.org/show_bug.cgi?id=1401851&sourceid=Mozilla-search)  RESOLVED FIXED in Firefox 57
- [1402373 - Slack's red badge favicon is shown for no reason and then isn't cleared when all messages are read](https://bugzilla.mozilla.org/show_bug.cgi?id=1402373&sourceid=Mozilla-search)  VERIFIED FIXED in Firefox 57
- [1403829 - YouTube icon doesn't look good in Firefox](https://bugzilla.mozilla.org/show_bug.cgi?id=1403829&sourceid=Mozilla-search)  RESOLVED FIXED in Firefox 58
- [1422289 - ContentLinkHandler should guess icon type from the extension when type is not defined](https://bugzilla.mozilla.org/show_bug.cgi?id=1422289&sourceid=Mozilla-search)  RESOLVED FIXED in Firefox 59
- [1449523 - ContentLinkHandler only picks perfectly sized icons](https://bugzilla.mozilla.org/show_bug.cgi?id=1449523&sourceid=Mozilla-search)  RESOLVED FIXED in Firefox 60

**Comment by grahamperrin** [comment]
Cross reference [Corrupt/wrong favicon for shortcut : waterfox](https://www.reddit.com/r/waterfox/comments/8ipw0q/corruptwrong_favicon_for_shortcut/)

----

> Mozilla bug 120352 - Site icon (favicon) tracking bug – dependency tree

I added a few more bugs to 120352 that are not yet in the dependency tree.

**Comment by grahamperrin** [comment]
#538

**Comment by MrL0G1C** [comment]
This is still happening and deleting the DB file for the icons doesn't work for long. How can code use the wrong site's icon for bookmarks?
