### ISSUE TITLE
Windows 7 Waterfox 56.0.2 Keeps asking to be set as default browser dispite already being default.

### ISSUE THREAD

**Issue by mikeloeven** [BrowserWorks/waterfox#363]
After updating to 56.0.2 I keep getting the set as default browser dialogue dispite already being the default browser. Clicking set as default does not resolve the issue and the do not check button is ignored

**Comment by grahamperrin** [comment]
https://github.com/MrAlex94/Waterfox/pull/362

**Comment by grahamperrin** [comment]
Cross reference https://www.reddit.com/r/waterfox/comments/7ov4a3/waterfox_5602_is_now_available_with_important/dsd00am/

**Comment by Ofunniku** [comment]
Current workaround: Go to "Default Programs" and set Waterfox as default there.

**Comment by mikeloeven** [comment]
Waterfox has no entry in default programs. there was a Firefox entry that had the waterfox icon but this did not resolve the issue. downloaded and ran a fresh copy of the installer attempting to repair. also no change. the default programs listing with the waterfox icon listed as firefox seems to indicate that something was not refactored properly

**Comment by Ofunniku** [comment]
![2018-01-09 13_42_56-set default programs](https://user-images.githubusercontent.com/5677089/34706515-3843dc30-f543-11e7-8c9f-39d9aa6f5f1a.png)

Yeah, that's most certainly an issue on your end.

**Comment by jdunn0** [comment]
After seeing this bug, I decided to test installing/uninstalling Waterfox 56.0.2 to see if I could figure out what is happening and it appears that Waterfox 56.0.2 is installing registry keys that use Waterfox instead of Firefox in all but one registry key via my patch in #348.
That one registry key should now be fixed via my patch in #362.

The one registry key is installed in Software\Clients\StartMenuInternet in HKCR if the user is doing a per-user install or HKLM or the user is doing a per-machine install.
It appears the installer will pick per-machine install if the user says yes to a UAC prompt and a per-user install if the user says no.

For Firefox and Waterfox, this key will be named either Firefox or Firefox-[AppModelId].
The [AppModelId] part is some ID generated upon install and is used to allow different browser registration entries to appear when multiple editions of Firefox are installed such as the Release version and the Developer version.

I'm not sure how the installer determines when to use Firefox or Firefox-[AppModelId] as the key name.
As long as it's picks the later then the default browser registration done by Waterfox 56.0.2 works just fine and both Firefox and Waterfox will show up in "Set Default Programs".
If however, it picks just "Firefox" and an existing install of Firefox also picked just "Firefox" then the setup will overwrite the key for a Firefox install and then only Waterfox will be available in "Set Default Programs".

My patch in #362 should change that to be either Waterfox or Waterfox-[AppModelId] instead eliminating the possible conflict with Firefox.

I have found on my computer that Firefox-[AppModelId] has been used by Firefox 57, Firefox 58 Developer Edition and Waterfox 56.0.2 so the default browser registration stayed separate for all 3.
If this was always the case then my patches in #348 would not be necessary except to avoid conflicts with older Firefox/Waterfox versions that didn't use the Firefox-[AppModelId] key but it doesn't seem to always be used.
I'm not sure when Firefox started using this key name or why it's only sometimes used.
I know even older versions used the executable name so it could be firefox.exe or waterfox.exe.

In theory it seems like the [ProgName]-[AppModelId] key name is the most unique and should always be used but maybe the installer will not change the key with doing an upgrade or repair install.
It would make sense during an upgrade to not change the key name if doing so would cause the browser to no longer be set as default if it was set as default previously as that could cause the prompt to set the default browser to appear for no apparent reason.
Though even in that case, the prompt should just appear once, the browser is set as default again and everything is fine.

@mikeloeven: 
I'm not sure what would cause an entry that says Firefox to appear but with a Waterfox icon.
I suggest to uninstall Waterfox and then reinstall it to see if the problem is fixed.
Profile Data is not removed by the uninstaller so it won't hurt to try.

**Comment by mikeloeven** [comment]
Uninstalled Waterfox and Firefox 57

Reinstalled Waterfox issue persists Waterfox has no entry in default programs menu

Any idea when a build with your fixes will be compiled
and in the meantime can the missing registry entry/ies be added manually ?

**Comment by LufiaSelan** [comment]
I am having this issue as well starting with the update to 56.0.2. I'm on Windows 7 and no longer use Firefox. Previous launch of Firefox was March 1, 2017 for me.

Definitely looking forward to this fix.

Many thanks to Waterfox and the people that keep it active!

**Comment by jdunn0** [comment]
@mikeloeven and @LufiaSelan:
I wrote a batch file that queries the registry for the keys involved in Browser Registration and saves the information to a file.
If you could run this batch file and attach the output file BrowserRegistrationKeys.txt file to a reply, it would be useful in helping me determine what happened with the Browser Registration configuration on your systems that is causing this issue.
The batch file only exports specific registry keys to the BrowserRegistrationKeys.txt that shouldn't have any personal data in them but you can check the file before uploading to make sure that it's just paths to installed web browsers and such if you want to (Because Github attachments can not be deleted, it can be good to check such things beforehand).
The batch file can be [downloaded here](https://cdn.rawgit.com/jdunn0/PublicScripts/master/GetBrowserRegistrationKeys.bat) and the source code is [available here](https://github.com/jdunn0/PublicScripts/blob/master/GetBrowserRegistrationKeys.bat).

**Comment by mikeloeven** [comment]
The batch file does not appear to complete process appears hung with no cpu use or memory activity. Closed it  with ctrl-c so file may be incomplete

[BrowserRegistrationKeys.txt](https://github.com/MrAlex94/Waterfox/files/1619508/BrowserRegistrationKeys.txt)

**Comment by LufiaSelan** [comment]
Batch file completed with some time given for the /s /f parts, takes a bit. Here's mine.

[BrowserRegistrationKeys.txt](https://github.com/MrAlex94/Waterfox/files/1619674/BrowserRegistrationKeys.txt)

**Comment by mikeloeven** [comment]
I was able to run a successful report the batch file completed this time 

[BrowserRegistrationKeys.txt](https://github.com/MrAlex94/Waterfox/files/1619799/BrowserRegistrationKeys.txt)

**Comment by MrAlex94** [comment]
Will fix this in the next update, thanks to @jdunn0.

**Comment by jdunn0** [comment]
@mikeloeven and @LufiaSelan:
Looking at the BrowserRegistrationKeys.txt files, it appears:
* The key Software\Classes\WaterfoxHTML-[AppModelId] is being created correctly
* The key Software\Classes\WaterfoxURL-[AppModelId] is being created correctly
* The key Software\Clients\StartMenuInternet\Firefox-[AppModelId] (Will be Software\Clients\StartMenuInternet\Waterfox-[AppModelId] in next version of Waterfox) is not being created
* The key Software\Clients\StartMenuInternet\WATERFOX.EXE exists which is probably from an older of Waterfox that was not removed for whatever reason.
This key has subkeys of Capabilities\FileAssociations and Capabilities\URLAssociations with values of "WaterfoxHTML" and "WaterfoxURL" which are keys that do not exist, the keys ending in "-[AppModelId]" are the keys that exist.

It appears that my patch #362 will not fix this problem of key Software\Clients\StartMenuInternet containing an older WATERFOX.exe key with references that are no longer valid instead of having a newer key ending in "-[AppModelId]" with valid references.

I think if you delete the registry key "HKEY_LOCAL_MACHINE\Software\Clients\StartMenuInternet\WATERFOX.EXE" and reinstall Waterfox the newer key will have to be installed as no older key will exist to use.
However needing the user to delete a registry key is a potentially dangerous (if the user is not experienced with the Registry Editor) and an inconvenient thing to require.
I will look at the installer code for Waterfox and maybe NSIS code too and if should removing the key be needed, then getting the installer to remove it.

**Comment by LufiaSelan** [comment]
Deleting registry key and reinstalling produced a new registry key in that location. Had to do a launch without a profile parameter, close that instance, and re-opening with the profile and the asking for default browser stopped.

**Comment by jdunn0** [comment]
Hmm, interesting.
I looked in the code at browser\installer\windows\nsis\shared.nsh and starting on line 541, there is a code that checks in the StartMenuInternet key if there is a sub key named ${FileMainEXE} and if that sub key exists then the code will just write the new information to that sub key instead of creating a new sub key named ${AppRegName}-$AppUserModelID.
It appears for @mikeloeven, @LufiaSelan and probably others, this code failed to work properly.

After looking at the code some more, it appears that because I had updated the code to use WaterfoxHTML/WaterfoxURL keys but as I didn't change ${AppRegName} to "Waterfox", this broke how the code figured things out so the "waterfox.exe" sub key was updated to use WaterfoxHTML/WaterfoxURL when it was suppose to use WaterfoxHTML-$AppUserModelID/WaterfoxURL-$AppUserModelID instead as the correct values.

It seems when the code runs and the older "waterfox.exe" sub key doesn't exist, then the a new key will be created with the correct values.
If someone's first installation of Waterfox is version that never used the "waterfox.exe" key then this issue would not happen.
In theory uninstalling Waterfox should delete the "waterfox.exe" key so when starting a new installation, it always uses the new key but appears that failed for some people too.
Maybe that because some entries got installed in both HKCU and HKLM and the uninstaller only knew about one of the keys, I'm not sure.

It does appear now that my patch in #362 that just sets ${AppRegName} to "Waterfox" instead of "Firefox" will in fact fix this issue.

The installer for the next release of Waterfox will need to handle the transition from using Firefox-$AppUserModelID to Waterfox-$AppUserModelID during an upgrade by deleting the old key and using the new key or renaming the old key to the new name if possible.
If not then for users upgrading from Waterfox 56.0.2 to the new version, users could end up with two entries in Default Programs for Waterfox.

I'll have to check if the installer can already handle this, if not then that will probably need to be corrected before the next release.

**Comment by LufiaSelan** [comment]
Confirmed that two entries appear in the registry section of HKEY_LOCAL_MACHINE\Software\Clients\StartMenuInternet for Firefox-$AppUserModeID and Waterfox-$AppUserModeID upon update to 56.0.3. I manually removed the Firefox one and everything appears to be working properly.

**Comment by GitCurious** [comment]
56.0.3 update worked _only_ after I _manually_ removed the old \StartMenuInternet\WATERFOX.EXE registry entry.

When using the WF 56.0.3 installer on it`s own, the original problem continued.

To clarify:  
On this computer, the Waterfox installer did NOT remove the problematic registry entry and did NOT fix the original problem.

**Comment by mikeloeven** [comment]
Can confirm updating to 56.0.3 did not resolve the issue. also a full uninstall reinstall did not help either. 

I finally ended up deleting the WATERFOX.EXE registry key manually and performed a reinstall. This did finally work although I was waiting and hoping the patch would do this automatically

**Comment by Telmesomething** [comment]
I had this problem myself and here's how I resolved it.

Go to this location in Windows Control Panel: **Control Panel\All Control Panel Items\Default Programs\Set Default Programs**. Click Waterfox to highlight it and then click "**Choose defaults for this program**". This will take you to the "**Set Program Associations**" menu. Checkmark all the boxes and then click OK. This is all you have to do.

Prior to using Waterfox I used Basilisk which I was quite happy with except that it keeps crashing. When I clicked the Make Default button in Windows 8.1 the following menu you see in the screenshot appeared. 

![no_ftp_option](https://user-images.githubusercontent.com/33827636/34946655-021757c6-fa08-11e7-97e7-edc179668846.PNG)

It looked from that there there was no way to enable Waterfox for FTP even though I was choosing to set Waterfox as the default browser each time. Also, just setting Waterfox as the default program handler in Windows CP isn't sufficient and you actually need to associate all the actions as well. Here's a screenshot of the CP where you have to click the bottom of the two options to take you to the file associations menu.

![set_default_file_associations](https://user-images.githubusercontent.com/33827636/34946909-e45f593a-fa08-11e7-942b-10463e4c09b8.PNG)

If the next menu simply checkmark all the file associations to make Waterfox the default browser.

![set_associations in windows cp](https://user-images.githubusercontent.com/33827636/34946994-14545e2e-fa09-11e7-8777-4880c61e5d57.PNG)

Once you've completed these steps you'll see that Waterfox has become the default browser in the General menu. 

![waterfox default](https://user-images.githubusercontent.com/33827636/34947197-b6c5bf68-fa09-11e7-8e6c-4075362f4f3e.PNG)

**Comment by grahamperrin** [comment]
#538
